language: node_js
notifications:
  email: false
os: linux
dist: focal  # or another version like bionic, xenial, etc.
node_js:
  - node
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install --save-dev @wojtekmaj/enzyme-adapter-react-17
  - npm i jest-enzyme
script:
  - npm test -- --coverage
after_success:
  - coverage
